checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    paths: ['docs/*', 'napps/*', 'tests/*', 'src/*', '.']
build:
    environment:
        python: 3.6.0
        postgresql: false
        redis: false
    dependencies:
        # "override" to not run inferred "python setup.py install" and
        # "pip install -r requirements.txt"
        override:
    tests:
        before:
            - pip install git+git://github.com/kytos/kytos.git
            - pip install -r requirements.txt -r requirements-dev.txt
        override:
            -
                command: 'python setup.py ci'
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'
